services: 
  db:
    image: mariadb:latest
    container_name: lagerverwaltung_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lagertool
      MYSQL_USER: lageruser
      MYSQL_PASSWORD: lagerpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lagerverwaltung_network

  db_UI:
    image: phpmyadmin:latest
    container_name: db_UI
    environment:
      PMA_HOST: lagerverwaltung_db
      PMA_USER: root
      PMA_PASSWORD: rootpass 
    ports: 
      - "8088:80"
    depends_on:
      - db
    networks: 
      - lagerverwaltung_network 

volumes:
  mariadb_data:

networks: 
  lagerverwaltung_network:
    driver: bridge