// <auto-generated />
using System;
using LagerverwaltungTool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LagerverwaltungTool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LagerverwaltungTool.Model.ArtikelModel", b =>
                {
                    b.Property<int>("ART_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ART_ID"));

                    b.Property<int?>("BesitzerId")
                        .HasColumnType("int");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Erfassungsdatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hostname")
                        .HasColumnType("longtext");

                    b.Property<string>("IPAdresse")
                        .HasColumnType("longtext");

                    b.Property<bool>("IstStatisch")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("MACAdresse")
                        .HasColumnType("longtext");

                    b.Property<int?>("Netz")
                        .HasColumnType("int");

                    b.Property<string>("Notizen")
                        .HasColumnType("longtext");

                    b.Property<string>("Ort")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ART_ID");

                    b.HasIndex("BesitzerId");

                    b.HasIndex("KategorieId");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.AusleihAntragModel", b =>
                {
                    b.Property<int>("REQ_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("REQ_ID"));

                    b.Property<string>("Begruendung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Erstellungsdatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notizen")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RueckgabeDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RueckgabeNotizen")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("REQ_ID");

                    b.HasIndex("UserId");

                    b.ToTable("AusleihAntraege");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.AusleihArtikelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ART_ID")
                        .HasColumnType("int");

                    b.Property<int>("Anzahl")
                        .HasColumnType("int");

                    b.Property<DateTime>("Bis")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("REQ_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Von")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ART_ID");

                    b.HasIndex("REQ_ID");

                    b.ToTable("AusleihArtikel");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.ChangeLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aktion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<int>("EintragId")
                        .HasColumnType("int");

                    b.Property<string>("Tabelle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChangeLogs");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.KategorieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kategorien");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswortHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rolle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.ArtikelModel", b =>
                {
                    b.HasOne("LagerverwaltungTool.Model.UserModel", "Besitzer")
                        .WithMany()
                        .HasForeignKey("BesitzerId");

                    b.HasOne("LagerverwaltungTool.Model.KategorieModel", "Kategorie")
                        .WithMany("Artikel")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Besitzer");

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.AusleihAntragModel", b =>
                {
                    b.HasOne("LagerverwaltungTool.Model.UserModel", "User")
                        .WithMany("Antraege")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.AusleihArtikelModel", b =>
                {
                    b.HasOne("LagerverwaltungTool.Model.ArtikelModel", "Artikel")
                        .WithMany("AusleihArtikel")
                        .HasForeignKey("ART_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagerverwaltungTool.Model.AusleihAntragModel", "Antrag")
                        .WithMany("Artikel")
                        .HasForeignKey("REQ_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrag");

                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.ChangeLogModel", b =>
                {
                    b.HasOne("LagerverwaltungTool.Model.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.ArtikelModel", b =>
                {
                    b.Navigation("AusleihArtikel");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.AusleihAntragModel", b =>
                {
                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.KategorieModel", b =>
                {
                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("LagerverwaltungTool.Model.UserModel", b =>
                {
                    b.Navigation("Antraege");
                });
#pragma warning restore 612, 618
        }
    }
}
